from .dashboard import dashboard
from .deposit import deposit
from .exchange import exchange_rate
from .recharge import recharge
from .transaction_history import transaction_history
from .transfer import transfer
from .receipt import *
from .profile import *
from .withdraw import *
from .beneficiary import *
from .password import *